const southAfricanCities = [
  'Aberdeen',
  'Acornhoek',
  'Adelaide',
  'Albertinia',
  'Alberton',
  'Alexandra',
  'Aliwal North',
  'Amanzimtoti',
  'Ballito',
  'Barberton',
  'Barkly East',
  'Barkly West',
  'Beaufort West',
  'Bedford',
  'Bela-Bela',
  'Bellville',
  'Benoni',
  'Bethal',
  'Bethlehem',
  'Bhisho',
  'Bisho',
  'Bityi',
  'Bizana',
  'Bloemfontein',
  'Blue Downs',
  'Botshabelo',
  'Boksburg',
  'Bothaville',
  'Brakpan',
  'Brandfort',
  'Brits',
  'Bronkhorstspruit',
  'Butterworth',
  'Caledon',
  'Calvinia',
  'Cape Town',
  'Carletonville',
  'Centurion',
  'Ceres',
  'Cofimvaba',
  'Colesberg',
  'Cradock',
  'Cullinan',
  'De Aar',
  'Delmas',
  'Dendron',
  'Despatch',
  'Dewetsdorp',
  'Dundee',
  'Durban',
  'East London',
  'Edenvale',
  'eMalahleni',
  'Empangeni',
  'Ermelo',
  'Eshowe',
  'Frankfort',
  'George',
  'Germiston',
  'Giyani',
  'Graaff-Reinet',
  'Grahamstown',
  'Graanlaagte',
  'Greytown',
  'Gqeberha',
  'Harrismith',
  'Heidelberg',
  'Hermanus',
  'Hoedspruit',
  'Hoopstad',
  'Howick',
  'Johannesburg',
  'Kathu',
  'Kempton Park',
  'Khayelitsha',
  'Kimberley',
  'King William\'s Town',
  'Klerksdorp',
  'Knysna',
  'Kokstad',
  'Komani',
  'Komatipoort',
  'Krugersdorp',
  'Kroonstad',
  'Kuruman',
  'KwaDukuza',
  'Lady Frere',
  'Ladybrand',
  'Ladysmith',
  'Lephalale',
  'Louis Trichardt',
  'Lusikisiki',
  'Mafikeng',
  'Mahikeng',
  'Malelane',
  'Mankweng',
  'Meyerton',
  'Midrand',
  'Mitchells Plain',
  'Mmabatho',
  'Modimolle',
  'Mokopane',
  'Montagu',
  'Moorreesburg',
  'Mossel Bay',
  'Mqanduli',
  'Mthatha',
  'Mtubatuba',
  'Musina',
  'Naboomspruit',
  'Newcastle',
  'Nigel',
  'Nkandla',
  'Nooitgedacht',
  'Nongoma',
  'Nqutu',
  'Odendaalsrus',
  'Orkney',
  'Oudtshoorn',
  'Paarl',
  'Pampierstad',
  'Parys',
  'Phalaborwa',
  'Piet Retief',
  'Pietermaritzburg',
  'Piketberg',
  'Pinetown',
  'Plettenberg Bay',
  'Polokwane',
  'Port Alfred',
  'Port Elizabeth',
  'Port Shepstone',
  'Potchefstroom',
  'Pretoria',
  'Queenstown',
  'Randburg',
  'Randfontein',
  'Richards Bay',
  'Ritchie',
  'Roodepoort',
  'Rustenburg',
  'Sabie',
  'Saldanha',
  'Sasolburg',
  'Secunda',
  'Sedgefield',
  'Sibasa',
  'Simon\'s Town',
  'Siyabuswa',
  'Somerset East',
  'Somerset West',
  'Soweto',
  'Springbok',
  'Springs',
  'Standerton',
  'Stanger',
  'Stellenbosch',
  'Steynsburg',
  'Stutterheim',
  'Tembisa',
  'Thabazimbi',
  'Theunissen',
  'Thohoyandou',
  'Tlokwe',
  'Tzaneen',
  'Uitenhage',
  'Ulundi',
  'Upington',
  'Vanderbijlpark',
  'Vereeniging',
  'Vredenburg',
  'Vryburg',
  'Vryheid',
  'Welkom',
  'Wellington',
  'White River',
  'Winburg',
  'Witbank',
  'Worcester',
  'Ysterplaat'
];

export default southAfricanCities;
